### ISSUE TITLE
Consider Communication as part of the curriculum

### ISSUE THREAD

**Issue by toddile** [isaqb-org/curriculum-eam#1]
Enterprise architecture is a complex and abstract topic. A main success factor is management buy-in. Therefore, the curriculum should include competency in communication to adequately address ea related topics for the key stakeholders. 
Suggested competency distribution:
Methodological: 25
Communication: 5
Key content for communication part:
-appropriate communication of stakeholders 
-use of analogies for explaining eam 
-visualization of eam
-storytelling for explaining the approach and benefits of eam

**Comment by rhoadesre** [comment]
I completely agree that communication is not only "a" main success factor, but "the" primary success factor. EAM-specific visualizations are already part of the curriculum; however, all of these points are already covered in the Soft-Skills curriculum. 

I think it would be helpful to at least add a sentence to the EAM curriculum to stress stakeholder-specific communication. However, I'm not sure which chapter would be appropriate to cover this topic. 

I'm open for suggestions.

**Comment by rhoadesre** [comment]
2023-05-22 EAM Meeting: 

Wir ergänzen den Lehrplan für dieses Thema nicht explizit.
Begründung:
Stakeholdergerechte Dokumentation und Visualisierung haben wir schon drin. Das Aufteilen wie vorgeschlagen kommt bei iSAQB noch nicht vor. Es gibt bereits eine Soft-Skills-Schulung für Kommunikation, um bspw. Storytelling abzudecken.
