### ISSUE TITLE
Bullet-Points unter 00b-basics/ 04-prerequisites-for-this-training.adoc

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-eam#22]
Ich habe versucht Bullet-Points zu erstellen, dies hat aber aus irgendeinem Grund nicht funktioniert (Branch: 00-Basics)

**Comment by programming-wolf** [comment]
Wenn du mit `*` Bullet points erzeugen willst, muss davor eine Zeile frei sein. 

```
Hier ist etwas Text. 

* Erster Punkt
* zweiter Punkt

Hier geht der Fließtext weiter. 
```

**Comment by rhoadesre** [comment]
Klar. Offensichtlich. 
:-(
Aber Danke! :-)
