### ISSUE TITLE
Mindestdauer

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-eam#24]
Unter 00b-basics/02-curriculum-structure-and-chronological-breakdown.adoc sowie in jedem Kapitel werden die empfohlene Mindestdauer aufgelistet. 

1. Bitte überprüfen und mein entsprechendes Issue kommentieren bzgl. euere Einschätzung
2. Ist es realistisch, dass alle Themen innerhalb drei Tagen durchgeführt werden?

**Comment by olaf-tesmer** [comment]
Bei der Schätzung der Mindestdauer wollte ich die benötigten Übungszeiten schätzen und das fällt mir sehr schwer. Denn ich habe festgestellt, dass unsere Lernziele ausschließlich durch die Verben "kennen", "verstehen", "erklären können" sowie "erkennen und berücksichtigen" (Kapitel Wechselwirkungen) beschrieben sind. Das Verb "können" fehlt. 
Frage: Ist das von uns so gewollt und damit überlassen wir dem Trainingsanbieter, an welchen Stellen Übungen gemacht werden? Woran machen wir fest, wo Übungen notwendig sind?

**Comment by rhoadesre** [comment]
Ich würde lieber, dass alles bei "kennen" usw. bleibt, sodass der Trainer entscheiden darf, welche Themen er/sie vertiefen möchte.
Bei der Advanced-Zertifizierung werden die Fallstudien sowieso allgemein gehalten und keine spezifischen Themen überprüfen, z.B. von der EAM- oder DDD-Schulungen.

**Comment by olaf-tesmer** [comment]
Ok, also schätzen wir eigentlich erstmal nur, wie lange es ohne Übungen mindestens dauert. Und dann legen wir einfach die mindeste Übungslänge fest?

**Comment by olaf-tesmer** [comment]
Hier meine Schätzung für die Mindestdauer (ohne Übungen). Ich bin da gefühlt an die "didaktische Schmerzgrenze" gegangen, weil es teilweise noch echt viele Inhalte in den Unterpunkten der Lernziele sind. Wenn man das wirklich in der Mindestzeit durchzieht, bleibt nicht viel Zeit für die eigentliche Trainingsdidaktik, z.B. Erfahrungsaustausch, Diskussion, Transfer in die eigene Praxis. 

LZ 1-1: 30 min
LZ 1-2: 30 min
LZ 1-3: 30 min
=> Kap. 1: 90 min

LZ 2.1: 60 min
LZ 2.2: 30 min
LZ 2.3: 20 min
LZ 2.4: 30 min
LZ 2.5: 30 min
LZ 2.6: 30 min
LZ 2.7: 30 min
LZ 2.8: 30 min
=> Kap. 2: 260 min

LZ 3.1: 30 min
LZ 3.2: 30 min
=> Kap 3: 60 min

LZ 4.1: 30 min
LZ 4.2: 30 min
LZ 4.3: 30 min
=> Kap 4: 90 min

**Comment by rhoadesre** [comment]
@Olaf: sind dann deine Schätzungen nur für den "Vortrag" ohne Übungen, Erfahrungsaustausch, Diskussion, Transfer in die eigene Praxis usw.? Das wäre insgesamt 500 Stunden.

Wenn wir mit 6 Stunden pro Tag (ohne Pausen) für drei Tage rechnen, haben wir 1.080 Stunden. D.h. ca. die Hälfte noch für Übungen usw., was realistisch wäre.

**Comment by rhoadesre** [comment]
Meine Einschätzung ist wie folgt. Anscheinend rede ich mehr als Olaf. :-)

LZ 1-1: 60 min
LZ 1-2: 60 min
LZ 1-3: 30 min
=> Kap. 1: 150 min

LZ 2.1: 80 min
LZ 2.2: 30 min
LZ 2.3: 40 min
LZ 2.4: 30 min
LZ 2.5: 30 min
LZ 2.6: 40 min
LZ 2.7: 40 min
LZ 2.8: 30 min
=> Kap. 2: 320 min

LZ 3.1: 40 min
LZ 3.2: 30 min
=> Kap 3: 70 min

LZ 4.1: 40 min
LZ 4.2: 40 min
LZ 4.3: 40 min
=> Kap 4: 120 min

Gesamtsumme: 660 min

**Comment by rhoadesre** [comment]
Meine Schlussfolgerung: knapp aber machbar.

Mein Vorschlag: genau wie wir das für den Soft-Skills-Lehrplan spezifizieren, scheriben wir explizit, dass die Themen dürfen verkürzt oder vertieft werden, abhängig vom Wissenstand der Teilnehmer.

Dann haben wir Flexibilität, um Themen wegzulassen, wenn es für die Gruppe Sinn macht.

**Comment by olaf-tesmer** [comment]
Meine Schätzung ist die reine Wissensvermittlung, d.h. die Theorie präsentieren, ggf. anhand eines Fallbeispiels vorstellen, Verständnisfragen. Also keine Übungen, kein langer Erfahrungsaustausch, keine lange Diskussion. Deshalb schrieb ich ja, dass es eine didaktische Schmerzgrenze ist, die ich so nie machen würde. 
Ich hatte die Aufgabe so verstanden, dass wir eine Mindestschätzung machen sollten. Für eine realistische, qualitativ hochwertige Schulung würde ich natürlich auch eher eine Verdopplung der Zeiten machen.
Ich finde den Vorschlag super, es wie im Soft-Skills-Lehrplan machen. 
Vielleicht könnten wir dann auch einfach, statt im Detail zu schätzen, eine ganz grobe Aufteilung der 1080 Stunden auf die Kapitel machen.

**Comment by rhoadesre** [comment]
Vorschlag: Anstatt Minuten, verwenden wir Prozentanteil. Unsere Zeiten sind zwar unterschiedlich, sind aber ähnlich nach Prozentanteil:
- Kapitel 1: ca. 20%
- Kapitel 2: ca. 50%
- Kapitel 3: ca. 10%
- Kapitel 4: ca. 20%

**Comment by olaf-tesmer** [comment]
Den Vorschlag finde ich gut. Das lässt sich auch algorithmisch unterstützen:
Es sind insgesamt 16 Lernziele. Dann sind rechnerisch davon:

    Kapitel 1: 19%
    Kapitel 2: 50%
    Kapitel 3: 13%
    Kapitel 4: 19%

**Comment by programming-wolf** [comment]
Bitte im finalen Dokument dann wieder Zeiten (Minuten) verwenden. 
Da es 30 Credit points hat, müssen es 1080 Minuten (3 Tage zu 6 Stunden) sein. 

Damit ist es dann auch wieder einheitlich mit allen anderen Curricula.

**Comment by rhoadesre** [comment]
Refer to Pull Request

**Comment by rhoadesre** [comment]
Refer to Pull Request
