### ISSUE TITLE
Themen entfernen, die für Softwarearchitekten nicht relevant sind.

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-eam#25]
Mit etwas Abstand bitte noch mal den ganzen Lehrplan überprüfen. Gibt es Themen, die wir entfernen könnten, da sie wenige Relevanz für Softwarearchitekten haben?

Bitte hier kommentieren, welche Themen, ihr als Kandidaten seht.

**Comment by olaf-tesmer** [comment]
Die Punkte von @rhoadesre sind für mich auch Streichkandidaten.
Zusätzlich schlage ich vor, das Thema Governance und Compliance zu streichen, indem wir einige Unterpunkte in anderen Kapiteln unterbringen. Für Unternehmensarchitekten ist das natürlich alles sehr wichtig, aber für Softwarearchitekten reichen meiner Meinung nach folgende Punkte:
In LZ 1.1 könnte man etwas über EAM und Governance einbringen:
* Beitrag von EAM zur Governance verstehen, z.B. Risikomanagement.

Folgende Punkte könnten ins Kapitel 5 verschoben werden, z.B. als neues LZ 5.4 "Architekturrollen und ihre Zusammenarbeit":
* Definition von unterschiedlichen Architektenrollen (z. B. Unternehmensarchitekt, Solution-Architekt und Softwarearchitekt) und -verantwortungen sowie deren Abgrenzungen und Zusammenhänge verstehen.
* Die Architektur- und Geschäftsdomänenübergreifende Zusammenarbeit als Erfolgsfaktor verstehen, z.B. durch Architektur-Communities.
* Die Wechselwirkung zwischen dem Unternehmensarchitekt und dem Softwarearchitekt kennen, z. B.:
**Unterstützung bei Architekturentscheidungen
** Erfahrungen aus den Projekten
** Austausch über neue Technologien

**Comment by rhoadesre** [comment]
> Die Punkte von @rhoadesre sind für mich auch Streichkandidaten. Zusätzlich schlage ich vor, das Thema Governance und Compliance zu streichen, indem wir einige Unterpunkte in anderen Kapiteln unterbringen. Für Unternehmensarchitekten ist das natürlich alles sehr wichtig, aber für Softwarearchitekten reichen meiner Meinung nach folgende Punkte: In LZ 1.1 könnte man etwas über EAM und Governance einbringen:
> 
> * Beitrag von EAM zur Governance verstehen, z.B. Risikomanagement.
> 
> Folgende Punkte könnten ins Kapitel 5 verschoben werden, z.B. als neues LZ 5.4 "Architekturrollen und ihre Zusammenarbeit":
> 
> * Definition von unterschiedlichen Architektenrollen (z. B. Unternehmensarchitekt, Solution-Architekt und Softwarearchitekt) und -verantwortungen sowie deren Abgrenzungen und Zusammenhänge verstehen.
> * Die Architektur- und Geschäftsdomänenübergreifende Zusammenarbeit als Erfolgsfaktor verstehen, z.B. durch Architektur-Communities.
> * Die Wechselwirkung zwischen dem Unternehmensarchitekt und dem Softwarearchitekt kennen, z. B.:
>   **Unterstützung bei Architekturentscheidungen
>   ** Erfahrungen aus den Projekten
>   ** Austausch über neue Technologien


Die Punkte finde ich gut. Allerdings ist mir das Thema Compliance auch wichtig, da Compliance ggf. Softwarearchtiektuen betreffen könnte. 

**Vorschlag: Entweder** 
1. Compliance verschlanken und unter "LZ 5-1  Einflüsse von der Unternehmensarchitektur auf die Softwarearchitektur" oder "LZ 1-2: EAM-Grundbegriffe" verschieben; oder 
2. Alle Themen unter Governance behalten (wo sie eigenlich gehören) und wesenthlich verschlanken.

Die Punkte unter Governance, die ich als Löschen:

LZ 4-1 (Governance Begriffe)
- Einordnung der Architektur-Governance in die IT-Unternehmensarchitektur kennen.
- Abgrenzung zwischen Architektur-Governance und Corporate- und IT-Governance kennen.
- Bezug auf EAM von Governance-Frameworks (z.B. COBIT, TOGAF Architecture Capability Framework) kennen.

LZ 4-2: (Organisation)
- Funktion, Aufgabe und Zusammensetzung von Architekturgremien erklären.

LZ 4-3: (Compliance)
- Funktion, Aufgabe und Zusammensetzung von Architekturgremien erklären.

**Comment by AndisAccount** [comment]
Meine Sicht: dazu:
- Impuls von Roger (https://github.com/isaqb-org/curriculum-eam/issues/25#issuecomment-1549544071)
   - LZ 1-2: EAM-Grundbegriffe (Nur den Punkt "Die Begrifflichkeiten der ISO 42010 erklären können: Stakeholder, Concerns, Architecture Views, Architecture Models"): streichen
   -  LZ 2-8: EAM-Reifegrad (Ganzes Kapitel): streichen
   -  LZ 3-2: Metamodelle (Ganzes Kapitel. Falls wir dieses Thema vom Kapitel entfernen, würde ich das ganze Kapitel löschen und das Thema bzgl. Repositories unter allgemeine Begriffe verschieben.): Ich würde Repositories und Metamodelle in ein LZ konsolidieren (denn Repositories basieren ja auf einem Metamodell) und nach "Grundbegriffe" verschieben. Kap. 3 kann dann entfallen
- Impuls von Christian (https://github.com/isaqb-org/curriculum-eam/issues/25#issuecomment-1550117186)
  - das neue LZ 5.4 "Architekturrollen und ihre Zusammenarbeit" finde ich gut, denn es betrifft ja nicht nur Governance/Compliance
  - dennoch würde ich versuchen, ein Kapitel "Architektur-Governance" beizubehalten, denn es ist ein wichtiger Punkt.

**Comment by rhoadesre** [comment]
Noch ein Streichkandidat für mich:
Unter "LZ 3-1: EAM-Repository", der Punkt: "Verschiedene Werkzeuge für die Erarbeitung und Verwaltung einer Unternehmensarchitektur kennen."

**Comment by rhoadesre** [comment]
Lass uns zu einem Konsens im morgigen Meeting kommen. 

Zusammenfassung der vorherigen Einträge:

**LZ 1-2: EAM-Grundbegriffe**
- Ein Punkt streichen: "Die Begrifflichkeiten der ISO 42010 erklären können: Stakeholder, Concerns, Architecture Views, Architecture Models"

**LZ 2-8: EAM-Reifegrad**
- Ganzes Kapitel streichen

**LZ 3-2: Metamodelle**
- ganzes Kapitel streichen und das Thema Metamodelle als ein Bullet-Point unter Repositories zusammenfassen.
- Vorschlag: den Punkt mit den entsprechenden Unterpunkten "Informationsarten in einem EAM-Repository benennen können, z.B.: ....." unter Repositories verschieben, da Architektur-Metamodelle auch darunter fallen.

**LZ 3-1: EAM-Repository**
- Den Punkt streichen: "Verschiedene Werkzeuge für die Erarbeitung und Verwaltung einer Unternehmensarchitektur kennen."
- Ganzes Kapitel unter "Grundbegriffe des Enterprise Architecture Managements" verschieben
- "03 Repositories und Metamodelle" Kapitel entsprechend löschen und die anderen Kapitel entsprechen neu nummieren.

Für das Governance Thema gibt es unterschiedliche Meinungen. Je mehr ich mich damit beschäftige, finde ich den Vorschlag von Olaf gut. Ich würde nur ein paar Punkte mehr zu Governance schreiben. Mein aktueller Vorschlag für Governance wäre wie folgt:

**Unter "Grundbegriffe des Enterprise Architecture Managements" aufnehmen:
LZ 1-4: Governance Begriffe und Konzepte**

- Definition, Ziele und Nutzen der Architektur-Governance kennen
- Aufgaben von Architektur-Governance verstehen, z.B. Risikomanagement, Compliance.
- Anforderungen und Akzeptanzkriterien als Basis für die Compliance verstehen.
- Methoden zur Überwachung und Beurteilung der Architektur-Compliance verstehen, z. B. nach TOGAF.

**Unter "Wechselwirkung zwischen Softwarearchitektur und Unternehmensarchitektur" verschieben:
LZ 5.4 Architekturrollen und ihre Zusammenarbeit**

- Definition von unterschiedlichen Architektenrollen (z. B. Unternehmensarchitekt, Solution-Architekt und Softwarearchitekt) und -verantwortungen sowie deren Abgrenzungen und Zusammenhänge verstehen.
- Die Architektur- und Geschäftsdomänenübergreifende Zusammenarbeit als Erfolgsfaktor verstehen, z.B. durch Architektur-Communities.
- Die Wechselwirkung zwischen dem Unternehmensarchitekt und dem Softwarearchitekt kennen, z. B.:
    - Unterstützung bei Architekturentscheidungen
    - Erfahrungen aus den Projekten
    - Austausch über neue Technologien
-

**Comment by rhoadesre** [comment]
2023-05-22 EAM-Meeting: Siehe Folgendes:

**LZ 1-2: EAM-Grundbegriffe**
- Punkt: "Die Begrifflichkeiten der ISO 42010 erklären können: Stakeholder, Concerns, Architecture Views, Architecture Models" auf "Stakeholdergerechte Dokumentation der Unternehmensarchitektur anhand von Views, Architecture Models etc., z.B. wie im ISO-42010-Standard beschrieben" unformulieren.

**LZ 2-8: EAM-Reifegrad**
- Ganzes Kapitel streichen
EAM-Meeting abgestimmt

**LZ 3-2: Metamodelle**
- ganzes Kapitel streichen und das Thema Metamodelle als ein Bullet-Point unter Repositories zusammenfassen.
- Vorschlag: den Punkt mit den entsprechenden Unterpunkten "Informationsarten in einem EAM-Repository benennen können, z.B.: ....." unter Repositories verschieben, da Architektur-Metamodelle auch darunter fallen.
EAM-Meeting: abgestimmt

**LZ 3-1: EAM-Repository**
- Den Punkt streichen: "Verschiedene Werkzeuge für die Erarbeitung und Verwaltung einer Unternehmensarchitektur kennen."
- Ganzes Kapitel unter "Grundbegriffe des Enterprise Architecture Managements" verschieben
- "03 Repositories und Metamodelle" Kapitel entsprechend löschen und die anderen Kapitel entsprechend neu nummieren.
EAM-Meeting: abgesimmt.

**Governance verschlanken**
EAM-Meeting: Governance als Kapitel lassen und mit den folgenden Themen verschlanken. Abgestimmt.

LZ 4-1: Governance Begriffe und Konzepte**
- Definition, Ziele und Nutzen der Architektur-Governance kennen
- Aufgaben von Architektur-Governance verstehen, z.B. Risikomanagement, Compliance.
- Schnittmengen zwischen Unternehmensarchitektur und Softwarearchitektur bzgl. Governance verstehen.
- Funktion, Aufgabe und Zusammensetzung von Architekturgremien kennen.
- Anforderungen und Akzeptanzkriterien als Basis für die Compliance verstehen.
- Methoden zur Überwachung und Beurteilung der Architektur-Compliance verstehen, z. B. nach TOGAF.

LZ 4-2 Organisation, Rollen und Verantwortungen**
- Definition von unterschiedlichen Architektenrollen (z. B. Unternehmensarchitekt, Solution-Architekt und Softwarearchitekt) und -verantwortungen sowie deren Abgrenzungen und Zusammenhänge verstehen.
- Die Architektur- und Geschäftsdomänenübergreifende Zusammenarbeit als Erfolgsfaktor verstehen, z.B. durch Architektur-Communities.
- Die Wechselwirkung zwischen dem Unternehmensarchitekt und dem Softwarearchitekt kennen, z. B.:
    - Unterstützung bei Architekturentscheidungen
    - Erfahrungen aus den Projekten
    - Austausch über neue Technologien

**Comment by rhoadesre** [comment]
Made changes. Refer to Pull-Request Streich-Kandidaten

**Comment by rhoadesre** [comment]
Changes made. Summary:

- Reformulated a point under LG 1-2.
- Removed LG 2-8 EAM Maturity Models.
- Merged LG 3-1 Repositories and LG 3-2 Metamodels, and moved them to the Definitions chapter.
- Deleted the Repositories chapter.
- Changed Learning Goal Numbers due to the deletion of the 03-Repositories chapter.
- Streamlined the Governance chapter.
- Also changed "LZ" to "LG" for the English version.
