### ISSUE TITLE
Referenzen überprüfen

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-eam#26]
1. Sind alle eure Referenzen im Kapitel aufgenommen worden?
2. Hat jedes Lernziel eine Referenz?

**Comment by rhoadesre** [comment]
2023-05-22 EAM Meeting: alle bitte explizit nachschauen, vor allem für das Kapitel Wechselwirkung

**Comment by programming-wolf** [comment]
Ist dieses Ticket hier auch fertig, @rhoadesre ?

**Comment by rhoadesre** [comment]
There were a couple of updates to the references. I assume that nobody else has any changes, so I'm closing this issue.
