### ISSUE TITLE
PDF generieren und überprüfen

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-eam#28]
Andreas?: PDF generieren. Funktioniert alles?

**Comment by rhoadesre** [comment]
Die Änderungen in der References-Datei muss noch in Main gemerged werden. Das sollte die Probleme (hoffentlich) lösen.

**Comment by AndisAccount** [comment]
Aktueller Build:
[gradlew.log](https://github.com/isaqb-org/curriculum-eam/files/11488236/gradlew.log)
[build-html.zip](https://github.com/isaqb-org/curriculum-eam/files/11488238/build-html.zip)
[curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11488239/curriculum-eam-de.pdf)
[curriculum-eam-en.pdf](https://github.com/isaqb-org/curriculum-eam/files/11488240/curriculum-eam-en.pdf)
[index.pdf](https://github.com/isaqb-org/curriculum-eam/files/11488242/index.pdf)

**Comment by AndisAccount** [comment]
Aktueller Build (mit Kap.5 und anderen Fixes):
[build-html.zip](https://github.com/isaqb-org/curriculum-eam/files/11497183/build-html.zip)
[curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497184/curriculum-eam-de.pdf)
[curriculum-eam-en.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497185/curriculum-eam-en.pdf)
[index.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497187/index.pdf)
[gradlew.log](https://github.com/isaqb-org/curriculum-eam/files/11497189/gradlew.log)

**Comment by rhoadesre** [comment]
Wo finden wir dann die generierten PDFs allgemein?

**Comment by rhoadesre** [comment]
> Aktueller Build (mit Kap.5 und anderen Fixes): [build-html.zip](https://github.com/isaqb-org/curriculum-eam/files/11497183/build-html.zip) [curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497184/curriculum-eam-de.pdf) [curriculum-eam-en.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497185/curriculum-eam-en.pdf) [index.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497187/index.pdf) [gradlew.log](https://github.com/isaqb-org/curriculum-eam/files/11497189/gradlew.log)

Hi Andreas,
in den PDFs ist immer noch das alte und nicht das neue Kapitel oder?

**Comment by programming-wolf** [comment]
Aktuell nur, wenn ihr sie lokal selbst generiert. Wenn ein Release Candidate gebaut wird, dann wird der unter https://public.isaqb.org/curriculum-eam/release-candidate veröffentlicht. 

Ich schaue gerade nach Möglichkeiten, dass die PDFs 
a) gespeichert werden nach einem Durchlauf und
b) dann für euch zum Download im PR stehen.

**Comment by AndisAccount** [comment]
> > Aktueller Build (mit Kap.5 und anderen Fixes): [build-html.zip](https://github.com/isaqb-org/curriculum-eam/files/11497183/build-html.zip) [curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497184/curriculum-eam-de.pdf) [curriculum-eam-en.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497185/curriculum-eam-en.pdf) [index.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497187/index.pdf) [gradlew.log](https://github.com/isaqb-org/curriculum-eam/files/11497189/gradlew.log)
> 
> Hi Andreas, in den PDFs ist immer noch das alte und nicht das neue Kapitel oder?

Stimmt, mein Fehler, sorry!

[gradlew.log](https://github.com/isaqb-org/curriculum-eam/files/11498071/gradlew.log)

**Comment by rhoadesre** [comment]
> Aktuell nur, wenn ihr sie lokal selbst generiert. Wenn ein Release Candidate gebaut wird, dann wird der unter https://public.isaqb.org/curriculum-eam/release-candidate veröffentlicht.
> 
> Ich schaue gerade nach Möglichkeiten, dass die PDFs a) gespeichert werden nach einem Durchlauf und b) dann für euch zum Download im PR stehen.

Ich schätze sehr deine Unterstützung!

**Comment by AndisAccount** [comment]
In der alten Datei  [curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11497184/curriculum-eam-de.pdf) war Kap. 5 "5. Unternehmensarchitektur-Frameworks", in der neuen [curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11498083/curriculum-eam-de.pdf) ist Kap. 5 jetzt "5. Wechselwirkung zwischen Softwarearchitektur und Unternehmensarchitektur".

Ich habe nochmal ein "git clone" in ein komplett leeres Verzeichnis gemacht und darin einen Build:
[gradlew.log](https://github.com/isaqb-org/curriculum-eam/files/11498525/gradlew.log)
[build-html.zip](https://github.com/isaqb-org/curriculum-eam/files/11498533/build-html.zip)
[curriculum-eam-de.pdf](https://github.com/isaqb-org/curriculum-eam/files/11498534/curriculum-eam-de.pdf)
[curriculum-eam-en.pdf](https://github.com/isaqb-org/curriculum-eam/files/11498536/curriculum-eam-en.pdf)
[index.pdf](https://github.com/isaqb-org/curriculum-eam/files/11498537/index.pdf)

Den Fix, dass das richtige Kapitel angezogen wird, ist ja in PR #38 erfolgt. PR #38 ist ja schon freigegeben. Wenn es innerhalb der Dateien von Kap 5 (z.B. an den Lernzielen) noch Änderungen gab brauchen die natürlich noch einen zusätzlichen PR.

**Comment by AndisAccount** [comment]
Hallo Ben, dein Build-Job funktioniert übrigens. Jetzt entstehen PFDs, ... Danke dafür!

**Comment by AndisAccount** [comment]
Nur weil wir darüber gesprochen hatten: Das Build.Log sieht man, wenn man auf den "Build"-Job klickt  
![image](https://github.com/isaqb-org/curriculum-eam/assets/126170665/b6b2d981-03c0-4016-9abe-58da2d7fdb69)
und dann den Step "Execute Gradle Build" aufklappt
![image](https://github.com/isaqb-org/curriculum-eam/assets/126170665/79eb8883-ad05-458e-98a1-b184c0a88200)
