### ISSUE TITLE
Nachricht "tag 'DE' not found in include file" auflösen

### ISSUE THREAD

**Issue by AndisAccount** [isaqb-org/curriculum-eam#40]
Wir haben immer weider folgende Warning im Build-Log: "tag 'DE' not found in include file:". Betrifft die Files 
- 00b-basics/00-basics.adoc
- 01-basic-terms/references.adoc
- 03-repositories/references.adoc
- 04-governance/references.adoc
- 05-interactions/references.adoc
- 06-frameworks/references.adoc
- 98-examples/00-examples.adoc

Bitte beheben, indem man am Ende der Datei folgendes einfügt (einfach Copy & Paste aus 02-procedures/references.adoc):

> // tag::REMARK[]
> // [NOTE]

> // tag::DE[]
> ////
> Eine Quelle wird über `<<label>>` referenziert. Dieses muss in `99-references/00-references.adoc` definiert sein.
> ////
> // end::DE[]

> // tag::EN[]
> ////
> A reference source is referenced via `<<label>>`. The label has to be defined in `99-references/00-references.adoc`.
> ////
> // end::EN[]

> // end::REMARK[]

Danke euch!

**Comment by programming-wolf** [comment]
Bitte REMARK _nicht_ mehr einbauen. Ich hab das überall rausgeworfen. Die Warnungen könnt ihr einfach ignorieren. Das ist halt bei den Strukturdateien so.

**Comment by programming-wolf** [comment]
REMARK hat keinen Effekt mehr, ich habe alles, was damit zu tun hatte, rausgeworfen, da es eh überhaupt nicht verwendet wurde.

**Comment by AndisAccount** [comment]
Ich fand den iSAQB-internen Hinweis, wo Referenzen einzupflegen sind, recht wertvoll. Deswegen habe ich ihn als Kommentar stehen lassen. Wäre es ok, wenn wir nur folgendes einbauen (ist ja nur ein Kommentar). Hintergrund: Ich mag es offen gestanden nicht so, wenn ich im build-log viele Fehler habe, die alle als "bekannt" durchgewunken werden weil man dann nämlich u.U. andere Fehler übersieht
Mein Vorschlag wäre also:  

// tag::DE[]
////
Eine Quelle wird über <<label>> referenziert. Dieses muss in 99-references/00-references.adoc definiert sein.
////
// end::DE[]

// tag::EN[]
////
A reference source is referenced via <<label>>. The label has to be defined in 99-references/00-references.adoc.
////
// end::EN[]

**Comment by rhoadesre** [comment]
2023-05-22 EAM-Meeting: abgestimmt
