### ISSUE TITLE
Lernziel verfeinern

### ISSUE THREAD

**Issue by cdonker** [isaqb-org/curriculum-eam#43]
https://github.com/isaqb-org/curriculum-eam/blob/f48ffc669f470b0bac8808ed412f5045a38c48d9/docs/02-procedures/02-learning-goals.adoc?plain=1#L35

Mir ist bei der Durchsicht nicht ganz klar, was dargestellt bzw. erklärt werden können muss.

**Comment by rhoadesre** [comment]
22.05.2023 EAM-Meeting: kein Änderungsbedarf.
