### ISSUE TITLE
Tippfehler - "i" fehlt

### ISSUE THREAD

**Issue by cdonker** [isaqb-org/curriculum-eam#44]
https://github.com/isaqb-org/curriculum-eam/blob/f48ffc669f470b0bac8808ed412f5045a38c48d9/docs/03-repositories/02-learning-goals.adoc?plain=1#L10

**Comment by rhoadesre** [comment]
+1

**Comment by rhoadesre** [comment]
Closed. Refer to Pull Request with the same name.
