### ISSUE TITLE
Rename a chapter number?

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-eam#47]
I removed chapter 3, which means that chapter 4 (Governance) should now be chapter 3, and chapter 5 (Interactions) should now be chapter 4. 

I renamed the learning goals inside each chapter, but I can't rename the directory itself.

Does anyone know how to rename a directory. If so, please let me know and/or just change the directory names directly.

**Comment by programming-wolf** [comment]
Just rename the directory and adjust the paths to them in the file that's referencing them.

**Comment by rhoadesre** [comment]
That's the problem. I couldn't find where you rename the directory

Mit freundlichen Grüßen,
Roger Rhoades
+49 152 53 44 33 55
***@***.***

________________________________

**Comment by programming-wolf** [comment]
I'm not quite sure I understand. 

- you rename the folder/directory either within the editor you use or in WindowsExplorer/Finder
- you search for the previous directory name in the structure file(s) or in the curriculum-eam.adoc

That should do it.

**Comment by rhoadesre** [comment]
Thanks. I was making changes directly in GitHub. I'll clone it to my PC and make changes there

Mit freundlichen Grüßen,
Roger Rhoades
+49 152 53 44 33 55
***@***.***

________________________________
