### ISSUE TITLE
Write Short Summary About Module EAM

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-eam#49]
Currently, the file `00b-basics/01-what-to-expect-of-this-module.adoc` does not contain purposeful content. 
Additionally, it is commented out in `00b-basics/00-basics.adoc`

It should, however, contain a proper short description of the contents of this module.

**Comment by AndisAccount** [comment]
Danke, Ben, für dieses Issue, das habe ich mir gestern auch gedacht, als ich doie PDF gesamtheitlich gelesen habe. @rhoadesre : Wie sollen wir es machen: Wollen wir den Text hier im Issue abstimmen oder reden wir bei dem nächsten Treffen darüber?

**Comment by rhoadesre** [comment]
Ich glaube, wir sind weit genug mit dem Lehrplan, dass wir mit GitHub issues ohne Meetings weiter arbeiten können.

Du kannst gerne einen Vorschlag machen

**Comment by AndisAccount** [comment]
_Ich würde im Kapitel "Grundlegendes" folgende Kapitelstruktur vorschlagen (vielleicht sollten wir für die Diskussion eine Confluence-Seite erstellen?):_

**Was ist das Ziel des Kurses?**
Der Kurs "EAM: Enterprise Architecture Management"  _(Anm.: sollten wir das Modul umbenennen in "Enterprise Architecture Management (EAM) für Software-Architekten"?)_  hat zum Ziel, die für einen Softwarearchitekten relevanten Themen aus dem Bereich EAM zu vermitteln. 

Warum ist dieses Wissen für einen Softwarearchitekten von Bedeutung?
Die Informationssysteme in den Unternehmen (und der Gesellschaft) werden kleinteiliger und zahlreicher. Dadurch steigt der Bedarf für Überblick und passende Gestaltung der Interaktionen. Prozess-Schritte (über IT-Systeme oder manuell) werden unternehmensweit enger und kleinteiliger miteinander verzahnt. Deswegen müssen Organisationen einen Zusammenhang für ihre gesamte Informationswelt herstellen und aufrecht erhalten. Ein Treiber dafür sind auch die steigenden Compliance-Anforderungen in den Unternehmen denn in einigen Branchen (z.B. Finanzindistrie) sind Unterlassungen in diesem Bereich sogar mit Gefängnis-Strafen belegt.

Auf der anderen Seite hat sich der Aufgabenbereich von EAM in den letzten Jahren gewandelt: EAM verantwortet inzwischen, dass Veränderungen in verschiedenen Bereichen (Strategie, Geschäftsfähigkeiten / Valuestreams , Technologie, Informationssysteme) zu einander kosistent sind und dass dies bei der Architektur von Anwendungen entsprechend berücksichtigt wird.

Zusammenfassend kann man also sagen, dass Enterprisearchitektur eines Unternehmens und die Softwarearchitektur einer Anwendung / eines Unternehmensbereichs Hand in Hand gehen müssen. Themen, die sich daraus für einen Softwarearchitekten ergeben sind z.B.: 
- Voraussetzungen für Architekturen mit loser Kopplung, d.h. z.B. DDD, APIs etc. 
- Anwendungsübergreifende Themen wie z.B. Anwendungs-Integration, anwendungsübergreifende Prozess wie Log-Management, ...
- Auswirkungen von Entscheidungen in der Softwarearchitektur auf die Enterprisearchitektur und umgekehrt
- Einbettung einer Anwendung in einen unternehmensweiten Rahmen (u.a. Anforderungen aus dem Bereich Compliance bzw. Unternehmensstrategie) und Berücksichtigung der Abhängigkeiten / Einflüsse in beide Richtungen

**Abgrenzung**
Der Kurs hat nicht primär die Enterprisearchitektur als Ziel sondern er soll den Software-Architekten aus ihrer Sicht einen Überblick zum Thema EAM bieten und die gegenseitige Beeinflussung dieser beiden Architekturbereiche und Schnittstellen zwischen ihnen behandeln. Dadurch mag er aber auch für Enterprisearchitekten interessant sein, die einen Außenblick auf das Thema EAM bekommen wollen um optimal mit Softwarearchitekten zusammenzuarbeiten.

**Voraussetzungen** 
_(angepasst auf Basis des bestehenden Drafts)_
Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:
- Grundlagen der Architekturentwicklung: Bedeutung und Abgrenzung von Architektur, Vorgehen, Einflüsse und Anforderungen, Architekturentscheidungen, Muster und Dokumentation mit Sichten, wie im CPSA-F Foundation Level vermittelt.

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:
- Praktische Erfahrung im Architekturbereich und Einblick in mindestens eine moderne Technologie oder Plattform zur Entwicklung von verteilten Anwendungen
- Kenntnis typischer Herausforderungen im Bereich von Unternehmensarchitekturen:
  - Definition von (IT-)Unternehmenszielen
  - Strategische (IT-)Planung
  - (IT-)Portfolio-Management
  - Applicaiton Lifecycle Management
  - IT-Infrastructure-Library (ITIL)

**Struktur des Lehrplans und empfohlene zeitliche Aufteilung**
_1:1 aus bestehendem Draft übernehmen_
**Dauer, Didaktik und weitere Details**
_1:1 aus bestehendem Draft übernehmen_
**Gliederung** des Lehrplans**
_1:1 aus bestehendem Draft übernehmen_
**Ergänzende Informationen, Begriffe, Übersetzungen**
 _1:1 aus bestehendem Draft übernehmen_

**Comment by rhoadesre** [comment]
Changed the file using Andreas' proposed description. Made minor changes and translated to english.

**Comment by rhoadesre** [comment]
Changed the file using Andreas' proposed description. Made minor changes and translated to english.
