### ISSUE TITLE
Suggestion: Change Subtitle of Module

### ISSUE THREAD

**Issue by AndisAccount** [isaqb-org/curriculum-eam#56]
I would suggest to change the Subtile of the Module to make it more precise: 
From:
- Module: EAM
- Subtitle: Enterprise Architecture Management

To:
- Module: EAM
- Subtitle: Enterprise Architecture Management for Software Architects

Reasoning: The course is not primarily for Enterprise Architects but the target-audience are Software Architects

**Comment by programming-wolf** [comment]
But isn't this kind of obvious, since it's an iSAQB (software architecture) module?

**Comment by rhoadesre** [comment]
I changed the name. I would also like to make this explizit

**Comment by rhoadesre** [comment]
Refer to Pull Request #57
